@startuml
interface IService

class ServiceFactory <<singleton>> {
	{static} -serviceFactoryInstance : ServiceFactory
	{static} +getInstance() : ServiceFactory
	-ServiceFactory()
	{static} -getImplName(String) : String
	+getService(String) : IService
}

class PropertyManager <<singleton>> {
	{static} -properties : Properties
	{static} -propsPath : String
	{static} +getProperty(String) : String
	{static} +loadProperties() : void
	{static} +loadProperties(String) : void
}

abstract class ITokenService {
	ITokenService : {static} +NAME : String
	ITokenService : {abstract} commit(Token) : void
	ITokenService : {abstract} getFileName(RSAPublicKey) : String
	ITokenService : {abstract} selectToken(RSAPublicKey) : Token
}

class FileSystemTokenServiceImpl {
	+commit(Token) : void
	+getFilename(RSAPublicKey) : String
	+selectToken(RSAPublicKey) : Token
}

IService --|> ITokenService
ITokenService --|> FileSystemTokenServiceImpl
@enduml